name: smart_distributor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_main.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/editor.png
    - assets/images/manager.png
    - assets/images/boss.png
    - assets/images/