// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyaRoIa9bNBLnjy_L6QMzLehI2EDr6zwg',
    appId: '1:654105791492:web:4207beffb6a668313bf951',
    messagingSenderId: '654105791492',
    projectId: 'smart-distribution-app',
    authDomain: 'smart-distribution-app.firebaseapp.com',
    storageBucket: 'smart-distribution-app.firebasestorage.app',
    measurementId: 'G-03TYPV7RCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_SGZ-8uxOg-oktRAIEj0Jp2p9d8IvNE',
    appId: '1:654105791492:android:815dcfb5d0b463773bf951',
    messagingSenderId: '654105791492',
    projectId: 'smart-distribution-app',
    storageBucket: 'smart-distribution-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBrFQVQxid82vSGe4ZLv5-CgEmiQ3gy4',
    appId: '1:654105791492:ios:6990ec95db3e1eab3bf951',
    messagingSenderId: '654105791492',
    projectId: 'smart-distribution-app',
    storageBucket: 'smart-distribution-app.firebasestorage.app',
    iosBundleId: 'com.example.smartDistributorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBrFQVQxid82vSGe4ZLv5-CgEmiQ3gy4',
    appId: '1:654105791492:ios:6990ec95db3e1eab3bf951',
    messagingSenderId: '654105791492',
    projectId: 'smart-distribution-app',
    storageBucket: 'smart-distribution-app.firebasestorage.app',
    iosBundleId: 'com.example.smartDistributorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyaRoIa9bNBLnjy_L6QMzLehI2EDr6zwg',
    appId: '1:654105791492:web:2d61822a5753ad4d3bf951',
    messagingSenderId: '654105791492',
    projectId: 'smart-distribution-app',
    authDomain: 'smart-distribution-app.firebaseapp.com',
    storageBucket: 'smart-distribution-app.firebasestorage.app',
    measurementId: 'G-TX9JLY0H21',
  );
<<<<<<< HEAD

=======
>>>>>>> 477952224e6bfe18f11e318aca95f34679924f54
}